export const PROGRAMS = [
    {
        id: 0,
        category: 'Fox',
        name: 'Swift Fox',
        image: null,
        type: 'Endurance Weightlifting',
        description: 'Weightlifing program focused on lower volume and higher reps to provide muscular endurance. 3 month minimum commitment.',
        cost: '$45/session' ,
    },
    {
        id: 1,
        category: 'Fox',
        name: 'Strong Fox',
        image: null,
        type: 'Strength Weightlifting',
        description: 'Weightlifing program focused on higher volume and lower reps to provide muscular strength. 3 month minimum commitment.',
        cost: '$45/session' ,
    },
    {
        id: 2,
        category: 'Fox',
        name: 'Foxy Fox',
        image: null,
        type: 'Physique Weightlifting',
        description: 'Weightlifing program focused on aesthetic appearance for competitions or lifestyle clients. 3 month minimum commitment.',
        cost: '$55/session' ,
    },
    {
        id: 3,
        category: 'Fox',
        name: 'Silver Fox',
        image: null,
        type: 'Longevity Weightlifting',
        description: 'Weightlifing program for clients in advanced age. Focus on ',
        cost: '$45/session' ,
    },
    {
        id: 4,
        category: 'Rabbit',
        name: 'Speedy Rabbit',
        image: null,
        type: 'Endurance Weightlifting',
        description: 'Weightlifing program focused on lower volume and higher reps to provide muscular endurance. 3 month minimum commitment.',
        cost: '$45/session' ,
    },
    {
        id: 5,
        category: 'Rabbit',
        name: 'Bunny Slopes',
        image: null,
        type: 'Endurance Weightlifting',
        description: 'Weightlifing program focused on lower volume and higher reps to provide muscular endurance. 3 month minimum commitment.',
        cost: '$45/session' ,
    },
    {
        id: 6,
        category: 'Rabbit',
        name: 'Winning by a Hare',
        image: null,
        type: 'Competitive Race Training',
        description: 'Weightlifing program focused on lower volume and higher reps to provide muscular endurance. 3 month minimum commitment.',
        cost: '$45/session' ,
    },
    {
        id: 7,
        category: 'Rabbit',
        name: 'Bunny Slopes',
        image: null,
        type: 'Youth Running Training',
        description: 'YRT: Weightlifing program focused on lower volume and higher reps to provide muscular endurance. 3 month minimum commitment.',
        cost: '$45/session' ,
    },
];